// USER REGISTRATION
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

// AUTHORIZE USER
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

// LOGIN & LOGOUT USER
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

// CLEAR ERRORS
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

// REQUEST PROPERTY
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_FAIL = 'REQUEST_FAIL';

// OFFERED PROPERTY
export const OFFER_SUCCESS = 'OFFER_SUCCESS';
export const OFFER_FAIL = 'OFFER_FAIL';

// CANCEL PROPERTY
export const CANCEL_SUCCESS = 'CANCEL_SUCCESS';
export const CANCEL_FAIL = 'CANCEL_FAIL';

// REJECT PROPERTY
export const REJECT_SUCCESS = 'REJECT_SUCCESS';
export const REJECT_FAIL = 'REJECT_FAIL';

// ACCEPT PROPERTY
export const ACCEPT_SUCCESS = 'ACCEPT_SUCCESS';
export const ACCEPT_FAIL = 'ACCEPT_FAIL';

